---
- name: Failed-deploy cleanup tasks
  hosts: openshift-nodes
  tasks:
    - name: Uninstall previously install packages
      package: name={{item}} state=absent
      with_items:
        - openshift
        - openshift-*
        - etcd
        - docker
        - docker-common


#    - name: Remove atomic-openshift files
#      file:
#        path: "{{item.path}}" #correction code
#        state: absent
#      with_fileglob:
#        - "/etc/sysconfig/atomic-openshift*"
#        - "/etc/sysconfig/docker*"

    - name: remove files and directories
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /etc/origin
        - /var/lib/openshift
        - /etc/etcd
        - /var/lib/etcd
        - /root/.kube
        - /etc/ansible/facts.d
        - /usr/share/openshift
        - /var/lib/docker

- name: Pre-deploy tasks
  hosts: all
  tasks:
    - name: Set hostnames according to inventory
      hostname:
        name: "{{ inventory_hostname }}"

- name: Pre-deploy tasks
  hosts: nodes
  tasks:
    - name: Yum update
      yum: name=* state=latest update_cache=yes
      when: ansible_os_family == "RedHat"

    - name: Copy hosts file
      template:
        src: hosts.txt
        dest: /etc/hosts

    - name: Install packages
      package: name={{item}} state=present
      with_items:
        - docker
        - docker-common
        - httpd-tools

    - name: Start docker
      service:
        name: docker
        state: started
        enabled: yes
